version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: risk-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senha123
    ports:
      - "1433:1433"