services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: risk-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MYSQL_SA_PASSWORD}
    ports:
      - "1433:1433"